### ISSUE TITLE
Compile error after requiring Aparite in a blank Crystal app.

### ISSUE THREAD

**Issue by rmarronnier** [watzon/apatite#2]
```bash
In /usr/share/crystal/src/comparable.cr:83:16

 83 | abstract def <=>(other : T)
                   ^--
Error: abstract `def Comparable(T)#<=>(other : T)` must be implemented by Apatite::LinearAlgebra::Vector(T)
```
is the result of a `crystal run` on a .cr file containing only `require "apatite"`.

I don't get this error when using Apatite in a lib and using `crystal spec`. Really weird.

**Comment by rmarronnier** [comment]
```
Crystal 0.30.1 [5e6a1b672] (2019-08-12)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
If needed

**Comment by watzon** [comment]
How weird, idk why this error would only be appearing in that specific instance, but it should be easy to fix.
