### ISSUE TITLE
Missing offset argument for #each_with_index method

### ISSUE THREAD

**Issue by rmarronnier** [watzon/apatite#3]
As per original enumerable `each_with_index` method : 
[source](https://github.com/crystal-lang/crystal/blob/5e6a1b672a8b06d2a819210b9905b806ec3d7c71/src/enumerable.cr#L403)

We could add the same `offset` argument in here : 
[source](https://github.com/watzon/apatite/blob/c19b317dcdeac142e8bda3c957a21679d1e62a01/src/apatite/linear_algebra/matrix.cr#L460)

Disclaimer : I need it to implement the Viterbi algorithm in a neat way :grin:

**Comment by watzon** [comment]
You can go ahead and submit a PR for it :+1:

**Comment by rmarronnier** [comment]
Well, it turned out I don't need this after all... but I needed `map_with_index` so I made a [PR](https://github.com/watzon/apatite/pull/4) for it :wink:

**Comment by watzon** [comment]
Fixed in #4
